#!/usr/bin/env sh

# Get the directory of the script to work from.
DIR=$(dirname "$0")
OS="$(uname)"

if [ -f "${DIR}/_esy/default/build/default/.ppx/let_anything_ppx/ppx.exe" ]; then
  # Use the dev build
  "${DIR}/_esy/default/build/default/.ppx/let_anything_ppx/ppx.exe" --as-ppx "$@"
elif [ "$OS" = "Darwin" ]; then
  # Run the macOS PPX
  "${DIR}/ppx-osx.exe" --as-ppx "$@"
elif [ "$OS" = "Linux" ]; then
  # Run the Linux PPX
  "${DIR}/ppx-linux.exe" --as-ppx "$@"
fi
