#!/usr/bin/env sh

# Get the directory of the script to work from.
DIR=$(dirname "$0")

if [ -f $DIR/_esy/default/build/default/.ppx/let_anything_ppx/ppx.exe ]; then
    # Use the dev build
    $DIR/_esy/default/build/default/.ppx/let_anything_ppx/ppx.exe --as-ppx $@
elif [ "$(uname)" = "Darwin" ]; then
    # Run the Mac PPX
    $DIR/ppx-osx.exe --as-ppx $@
elif [ "$(expr substr $(uname -s) 1 5)" = "Linux" ]; then
    # Run the Linux PPX
    $DIR/ppx-linux.exe --as-ppx $@
fi